---

# all handlers will run at the end of the play
- name: run normal
  hosts: all
  roles:
    - role: r1
    - role: r2
    - role: r3

# here the handlers of each role will be run at the end of the role itself
- name: run with flushhandlers
  hosts: all
  roles:
    - role: r1
    - flushhandlers
    - role: r2
    - flushhandlers
    - role: r3
