---

- name: install apache
  apt:
    name: apache2

- name: stop apache for demonstration purposes
  service:
    name: apache2
    state: stopped

- name: configure apache
  template:
    src: config.j2
    dest: /etc/apache2/sites-available/000-default.conf
    mode: 0644
  when: updatecfg | default(true) | bool
  register: cfgchanged

- name: register apache2 desired state
  set_fact:
    apache_service_state: restarted
  when: cfgchanged.changed | default(false)  # noqa no-handler

- name: second change
  block:
    - name: trigger second change
      set_fact:
        additionalstuff: " ... trigger second change"

    - name: configure apache 2
      template:
        src: config.j2
        dest: /etc/apache2/sites-available/000-default.conf
        mode: 0644
      register: cfgchanged2

    - name: register apache2 desired state 2
      set_fact:
        apache_service_state: restarted
      when: cfgchanged2.changed | default(false)  # noqa no-handler
  when: updatecfg2 | default(false) | bool

- name: ensure apache service state is {{ apache_service_state | default('started') }}
  service:
    name: apache2
    state: "{{ apache_service_state | default('started') }}"
