---

- name: install apache
  apt:
    name: apache2

- name: stop apache for demonstration purposes
  service:
    name: apache2
    state: stopped

- name: configure apache
  template:
    src: config.j2
    dest: /etc/apache2/sites-available/000-default.conf
    mode: 0644
  when: updatecfg | default(true) | bool
  notify: restart apache2

- name: ensure apache service state is started
  service:
    name: apache2
    state: started
