---

- name: install apache
  apt:
    name: apache2

- name: configure apache
  template:
    src: config.j2
    dest: /etc/apache2/sites-available/000-default.conf
    mode: 0644
  when: updatecfg | default(true) | bool
  notify: restart apache2

- name: run all notified handlers at this point
  meta: flush_handlers

- name: ensure apache service state is started
  service:
    name: apache2
    state: started

- name: check apache is listening on port 80
  wait_for:
    port: 80
    timeout: 2
    msg: "Timeout waiting for 80 to respond"
